### ISSUE TITLE
iOS DDI

### ISSUE THREAD

**Issue by ItsMeEC** [intothedarkness/GPS-Simulator#12]
Hello,

Wondering if the new 14.1 update will be added to the repo soon?
Love the sim.

Thanks alot.

**Comment by heebybeeby** [comment]
Yes! This please.

**Comment by intothedarkness** [comment]
done

**Comment by ntomita** [comment]
14.2 just came out and need to be added to the repo for provision! Thanks for the great tool! @intothedarkness
