### ISSUE TITLE
Bing Maps Windows Presentation Foundation Control Download GONE / no mirrors

### ISSUE THREAD

**Issue by yuprule** [intothedarkness/GPS-Simulator#16]
Hello.  I tried to download the Bing Maps Windows Presentation Foundation Control from Microsoft, it's GONE.  I tried googling to find a mirror, none.  Even tried searching for the exact file name and ended up on virus infested websites :(

Do you have a safe mirror I can download it from?

Thank you!

**Comment by intothedarkness** [comment]
you can try the nuget package instead
https://www.nuget.org/packages/Microsoft.Maps.MapControl.WPF/
