### ISSUE TITLE
How do you manually provision device? 

### ISSUE THREAD

**Issue by XDynaqmics** [intothedarkness/GPS-Simulator#17]
I've got the correct DeveloperDiskImage.dmg and DeveloperDiskImage.dmg.signature file but I'm not sure about the "ideviceimagemounter.exe". Could you please elaborate?

**Comment by Converjance** [comment]
Use command prompt.

"C:\Users\<user profile>\Downloads\GPS-Simulator-master\GPS-Simulator-master\win-x64\ideviceimagemounter.exe" C:\Users\<user profile>\Downloads\GPS-Simulator-master\GPS-Simulator-master\DDILocalRepo\DeveloperDiskImage.dmg

You will need to manually provision every time. If you try to provision in the simulator it may give you problems. A quick way to provision is to create a .bat file

If you have issues provisioning try:

1. disconnect phone
2. reboot phone
3. close GPS-Simulator
4. delete both DeveloperDiskImage.dmg files from \GPS-Simulator-master\DDILocalRepo 
5. Re-extract from the version of your phone into the same directory (you will have to move the files from the newly created folder into the \GPS-Simulator-master\DDILocalRepo 
6. use cmd to re-provision
7. open GPS-Simulator
8. provision device (you should see a message "Device is already properly provisioned!")
