### ISSUE TITLE
Restore iphone location

### ISSUE THREAD

**Issue by benjamin658** [intothedarkness/GPS-Simulator#2]
Thanks for the excellent app and it works as expect on my Windows 10 with iPhone XS iOS 13.6.

My question is that is it possible to restore iPhone's location after unplug from the PC without restarting iPhone?

thanks.

**Comment by intothedarkness** [comment]
yeah, definitely is doable, will try to add that when I got cycle.

**Comment by intothedarkness** [comment]
made a little research, it seems the imobiledevice lib doesn't support it. :(
