### ISSUE TITLE
Possible Updates

### ISSUE THREAD

**Issue by robertojiang** [intothedarkness/GPS-Simulator#5]
Hi, would it be possible to add the following:

1. End at location (Ends walking once it reaches it's location)
2. Walk back from current location (If you've only walked half the route and need it to go back to the starting point)
3. Set personal speeds (I understand that there are walk, run and drive -- but let's say my roads here are 60km/h, then switches to 70km/h, I would prefer to set those speeds or if I want the walk setting to be faster or slower or the run setting to be faster or slower. I would still enjoy the three toggle, but have a 4th option with a fill in box for custom speed)
4. Add a button for stop and drift, not sure how to code that but when you're in one place, the GPS will still drift to different locations
5. Allow changing default startup location? I've accidentally doubleclicked on the default map before with my trackpad and it warped me to Seattle when I'm from Ontario, Canada

**Comment by intothedarkness** [comment]
addressed a few request.

**Comment by intothedarkness** [comment]
most of the requests are added.
